"""Export a session as a reproducible shell script."""

from breadcrumb.session import Session

SHEBANG = "#!/usr/bin/env bash"
SET_FLAGS = "set -euo pipefail"


def export_to_script(session: Session, include_notes: bool = True, include_cwd_changes: bool = True) -> str:
    lines = [
        SHEBANG,
        SET_FLAGS,
        "",
        f"# Session: {session.name}",
        f"# Generated by breadcrumb-cli",
        "",
    ]

    prev_cwd = None
    for i, step in enumerate(session.steps, start=1):
        if include_notes and step.note:
            lines.append(f"# {step.note}")

        if include_cwd_changes and step.cwd != prev_cwd:
            lines.append(f"cd {step.cwd}")
            prev_cwd = step.cwd

        lines.append(step.command)
        lines.append("")

    return "\n".join(lines)


def write_script(session: Session, output_path: str, **kwargs) -> None:
    script = export_to_script(session, **kwargs)
    with open(output_path, "w") as f:
        f.write(script)
    import os
    os.chmod(output_path, 0o755)
